### PR TITLE
Loud warnings

### PR DESCRIPTION
**Pull request by SzySteve**
screen shot 2017-12-18 at 2 26 50 pm

### CODE REVIEW

**Comment by yoshizzle** [comment]
I'm going to assume this was approved by caker and/or Howie.

From a technical PR perspective I approved.

**Comment by SzySteve** [comment]
`looks good to me` - Slack Howie

**Comment by SzySteve** [comment]
@Dorthu tomorrow

**Comment by Dorthu** [comment]
Please point this at master

**Pull request merged**
